project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - Sessions/W1_Intro_and_data/index.qmd
    - Labs/W1_Intro_and_data/index.qmd

website:
  title: "Quantitative Methods"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        file: index.qmd
      - section: "Sessions"
        contents:
          - text: "Week 1: Introduction and Data"
            file: Sessions/W1_Intro_and_data/index.qmd
      - section: "Labs"
        contents:
          - text: "Week 1: Data Lab"
            file: Labs/W1_Intro_and_data/index.qmd

format:
  html:
    theme: cosmo
    toc: true
    embed-resources: false
    highlight-style: github
    code-copy: hover
    code-line-numbers: true
